[program:laravel-queue]
process_name=%(program_name)s_%(process_num)02d

command=/usr/bin/php.default /home/botcamap.fun/artisan queue:work --sleep=1 --tries=3 --timeout=90

autostart=true
autorestart=true

user=botca8174

numprocs=1
redirect_stderr=true
stdout_logfile=/home/botcamap.fun/storage/logs/queue.log
stopwaitsecs=3600